config/routes.rb
Rails.application.routes.draw do
  root "public/homes#top"
  namespace :public  do
    # get "/"=> "homes#top"
    get "about"=> "homes#about"
  end

  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
}



devise_for :public, controllers: {
  sessions:      'public/sessions',
  passwords:     'public/passwords',
  registrations: 'public/registrations'
}



 namespace :admin do
    get "/"=> "homes#top"
     resources :genres, only: [:index, :create, :edit, :update]
     resources :items, only: [:show, :index, :new, :create, :edit, :update]
     resources :customers,only: [:index,:show,:edit,:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :shipping_addresses, dependent: :destroy


       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord

   belongs_to :genre
   has_many :cart_items
   has_many :order_details

   has_one_attached :image
   validates :name, {presence: true}
   validates :introduction, {presence: true}
   validates :price, {presence: true}
   def add_tax_price
     (self.price * 1.10).round

   end
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admins::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
     if @genre.save
      redirect_to admins_genres_path
     else
       flash[:genre_created_error] = "ジャンル名を入力してください"
       redirect_to 
     end
  end

  def update

  end
end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

app/controllers/admin/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]
  
  def new
     @item = Item.new
  end
  def index
     @items = Item.all
     @item =Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
    redirect_to
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_items_(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admins_items_path(@item)
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
end
private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price,:is_active)

  end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
   #def destroy
   # super
   #end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  def new
     @items = Item.new
  end
  def index
     @items = Item.all
     @item =Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
    redirect_to
    end
  end

  def update
  end

  def show
    @item = Item.find(params[:id])
  end
end
private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price,:is_active)

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base




def after_sign_in_path_for(resource)
      case resource
        when Admin
          admins_items_path
        when Customer
          root_path
      end
end





  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
    end
end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="nav navbar-nav navbar-left">
      <h1 class="sample"><%= link_to image_tag("logo.png"), root_path, data: {"turbolinks" => false}, style: "font-family: HiraMinPro-W6; color: #000000;" %></h1><%# image_tag("img_logo.png") %>
  </nav>
  <nav>
    
  </nav>
</header>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


  <body>
    <% if public_signed_in? %>
      <li>
        <%= link_to "publics/items" do %>
        <span>商品一覧</span>
         <% end %>
      </li>
      <li >
         <%= link_to destroy_public_session_path, method: :delete do %>
         <span > ログアウト</span>
          <% end %>
     </li>
    <% elsif admin_signed_in? %>
     <li>
        <%= link_to "/admins/items"  do %>
        <span > 商品一覧</span>
       <% end %>
     </li>
     <li>
        <%= link_to "/admins/genres"  do %>
        <span > ジャンル一覧</span>
        <% end %>
     </li>
     <li >
         <%= link_to destroy_admin_session_path, method: :delete do %>
         <span > ログアウト</span>
          <% end %>
     </li>

     <% else %>
          <li>
             <%= link_to "/publics/items" do %>
             <span >商品一覧</span>
              <% end %>
          </li>
          <li >
            <%= link_to "/publics/about" do %>
            <span>About</span>
             <% end %>
          </li>
          <li>
             <%= link_to new_public_registration_path do %>
             <span> 新規登録</span>
              <% end %>
          </li>
          <li >
            <%= link_to new_public_session_path do %>
            <span>ログイン</span>
             <% end %>
          </li>
    <% end %>
    <%= yield %>
    <footer>

    </footer>
  </body>
</html>